// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// newfft
NumericVector newfft(NumericVector x);
RcppExport SEXP _QForm_newfft(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(newfft(x));
    return rcpp_result_gen;
END_RCPP
}
// newfft2
NumericVector newfft2(NumericVector re, NumericVector im);
RcppExport SEXP _QForm_newfft2(SEXP reSEXP, SEXP imSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type re(reSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    rcpp_result_gen = Rcpp::wrap(newfft2(re, im));
    return rcpp_result_gen;
END_RCPP
}
// newfft3
NumericVector newfft3(NumericVector k, NumericVector lambda, NumericVector ncps, double a, double b, int n);
RcppExport SEXP _QForm_newfft3(SEXP kSEXP, SEXP lambdaSEXP, SEXP ncpsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ncps(ncpsSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(newfft3(k, lambda, ncps, a, b, n));
    return rcpp_result_gen;
END_RCPP
}
// newfft4
NumericVector newfft4(NumericVector k, NumericVector lambda, NumericVector ncps, double a, double b, int n, int nthreads);
RcppExport SEXP _QForm_newfft4(SEXP kSEXP, SEXP lambdaSEXP, SEXP ncpsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ncps(ncpsSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(newfft4(k, lambda, ncps, a, b, n, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// machine_eps
double machine_eps(double value);
RcppExport SEXP _QForm_machine_eps(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(machine_eps(value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QForm_newfft", (DL_FUNC) &_QForm_newfft, 1},
    {"_QForm_newfft2", (DL_FUNC) &_QForm_newfft2, 2},
    {"_QForm_newfft3", (DL_FUNC) &_QForm_newfft3, 6},
    {"_QForm_newfft4", (DL_FUNC) &_QForm_newfft4, 7},
    {"_QForm_machine_eps", (DL_FUNC) &_QForm_machine_eps, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_QForm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
