# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

newfft <- function(x) {
    .Call('_QForm_newfft', PACKAGE = 'QForm', x)
}

newfft2 <- function(re, im) {
    .Call('_QForm_newfft2', PACKAGE = 'QForm', re, im)
}

newfft3 <- function(k, lambda, ncps, a, b, n) {
    .Call('_QForm_newfft3', PACKAGE = 'QForm', k, lambda, ncps, a, b, n)
}

newfft4 <- function(k, lambda, ncps, a, b, n, nthreads) {
    .Call('_QForm_newfft4', PACKAGE = 'QForm', k, lambda, ncps, a, b, n, nthreads)
}

machine_eps <- function(value) {
    .Call('_QForm_machine_eps', PACKAGE = 'QForm', value)
}

